language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - OUNIT_CI=true PINS="gettext.0.4.0:. gettext-stub.0.4.0:. gettext-camomile.0.4.0:."
addons:
  homebrew:
    packages: gettext
    update: true
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
matrix:
  include:
    - name: "gettext: reverse dependencies with linux"
      os: linux
      env: OCAML_VERSION=4.08 PACKAGE="gettext" REVDEPS="true"

    - name: "gettext-stub: reverse dependencies with linux"
      os: linux
      env: OCAML_VERSION=4.08 PACKAGE="gettext-stub" REVDEPS="true"

    - name: "gettext-camomile: reverse dependencies with linux"
      os: linux
      env: OCAML_VERSION=4.08 PACKAGE="gettext-camomile" REVDEPS="true"

    - name: "gettext: MacOSX"
      os: osx
      env: OCAML_VERSION=4.08 PACKAGE="gettext"

    - name: "gettext-stub: MacOSX"
      os: osx
      env: OCAML_VERSION=4.08 PACKAGE="gettext-stub"

    - name: "gettext-camomile: MacOSX"
      os: osx
      env: OCAML_VERSION=4.08 PACKAGE="gettext-camomile"
